### ISSUE TITLE
License for pretrained models

### ISSUE THREAD

**Issue by adamjstewart** [zhu-xlab/SSL4EO-S12#1]
What license are your pretrained models released under?

We would like to add your pretrained models to [TorchGeo](https://github.com/microsoft/torchgeo/pull/917), but some of the pretrained models require further modifications [[1]](https://github.com/zhu-xlab/SSL4EO-S12/blob/d2868adfada65e40910bfcedfc49bc3b20df2248/src/benchmark/transfer_classification/linear_BE_moco.py#L253,L263), [[2]](https://github.com/zhu-xlab/SSL4EO-S12/blob/1a668f76fd46762a19780293675a6e23e5204e72/src/benchmark/transfer_classification/linear_BE_moco_v3.py#L204-L212) to make them suitable for loading. We could make these modifications on the fly if necessary, but it would be easier to make these modifications a single time and rehost the modified weights. But I'm not sure what license you're using so I'm not sure if that's allowed.

Alternatively, would you be willing to release a modified version of your weights that can be loaded directly into timm without modifications? @nilsleh not sure if you have permission to do this yourself.

**Comment by wangyi111** [comment]
Hi there! Both the dataset and weights are under CC-BY-4.0, so feel free to adapt:)

**Comment by adamjstewart** [comment]
Perfect, that makes things much easier. Hopefully this will make it easier for others to reuse these weights as well!

**Comment by adamjstewart** [comment]
> Both the dataset and weights are under CC-BY-4.0

It may be a good idea to add a LICENSE file to this repository so that this is explicitly documented.
