### ISSUE TITLE
could you please public  the code of fine-tune.py from mae and the training log？

### ISSUE THREAD

**Issue by DDKdakuan** [zhu-xlab/SSL4EO-S12#11]

**Comment by wangyi111** [comment]
Hi @DDKdakuan , sorry for the late reply. For fine tuning MAE we used the same script as linear, i.e. `linear_XX_MAE.py` (there's a `--fine_tune`  argument). You could also adapt the fine tuning script of official MAE, which replaces the optimizer with AdamW, and optionally uses "mixup/cutmix" augmentation. For fair comparison among methods, we didn't use "mixup/cutmix". And for the optimizer, I tested SGD similar as AdamW in our case.
