### ISSUE TITLE
General Query regarding paper

### ISSUE THREAD

**Issue by vishalned** [zhu-xlab/SSL4EO-S12#15]
Hello,

I just have a general question regarding the paper. What was your main intuition behind downloading a tile of size 2640x2640m. (Why not just download images of same size as what you need, in this case it would be 2240x2240m). 

Also is there any intuition on choosing the image size of 224 or 112. I am just trying to understand how one decides if the image size is supposed to be 224 or 256 or even larger like 512. 

Thanks in advance

**Comment by wangyi111** [comment]
Hi! Thanks for your question. There are several factors that we consider:
- sentinel-2 data has a ground sampling distance of 60m, 30m and 10m depends on different bands, which we upsample to a common 10m. This means the downloaded image size has to be divisible by 6, leading to a choice between e.g. 132x132, 264x264, 528x528.
- when people develop those popular model backbones like resnet or vit, the images they use are usually ImageNet or similar and commonly has a size of 256x256. We try to match a similar size such that those standard models can be easily used without scaling issue, as input size can have a big influence on the model performance. Take an extreme example, when you use resnet50 (32x downscale) and have image size 16x16, the second last downsampling layers would already downscale the feature to 1x1, this is a bit too much for downsampling.
- we crop the image to 224x224 from 264x264 to match a standard ResNet/ViT also, as they are designed in the same way on ImageNet. This also makes the comparison between our model and e.g. ImageNet pretrained model (which is trained on ImageNet in this way) fair.

As for the choice of image size in practice (e.g. if you want to use our model on your custom data), there is an ablation study in our paper (appendix-3.B.). The short conclusion is that the bigger the input size, the better the performance. However, bigger input size also consumes more memory, so you may need to balance.

**Comment by vishalned** [comment]
Thanks for the explanation.
