### ISSUE TITLE
Difficulties Unzipping Downloads

### ISSUE THREAD

**Issue by tomburgert** [zhu-xlab/SSL4EO-S12#16]
Dear authors, 

in contrast to another dataset that was released by you and provided through tum cloud (So2Sat), I face some diffculties downloading the SS4LEO-S12 dataset from https://dataserv.ub.tum.de/index.php/s/m1660427.001?path=%2Fssl4eo-s12.

After wget the download link for s2_l2a.tar.gz, I receive a very big file of 239GB, but neither unzip or tar work for this downloaded file. Could you double check if the file might be corrupted? Or, instead, could provide me with a working link from which I could download the dataset per wget?

Best,
Tom

**Comment by wangyi111** [comment]
Hi Tom, thanks for reporting. What was your error message when unzipping? The s2_l2a.tar.gz should be around 500GB (1TB extracted with 14M files). Could it be the downloading was interrupted? What about trying rsync? 

Optionally try out our compressed 8-bit version at https://mediatum.ub.tum.de/1702379? This is only around 50GB and should be easier to try.

**Comment by tomburgert** [comment]
Hi, I actually now managed to download it without any data loss. It works now. But thanks for the quick answer, anyways!
