### ISSUE TITLE
Reproducing the segmentation results (DFC2020)

### ISSUE THREAD

**Issue by RyanAmaudruz** [zhu-xlab/SSL4EO-S12#19]
Hi,
I would be interesting in trying to reproduce the results you obtained for the land cover segmentation tasks. I saw that you link two repos (DeepAI4EO/RSI-Segmentation and DeepAI4EO/Dataset4EO) in your .md file.
Would it be possible to get some pointers on how one might use both repos to reproduce your results?
Many thanks

**Comment by wangyi111** [comment]
Hi! Sorry for the late reply. RSI-Segmentation is based on [openmmlab's mmsegmentation](https://github.com/open-mmlab/mmsegmentation) while [Datase4EO](https://github.com/EarthNets/Dataset4EO) provides some convenient remote sensing dataset classes with pytorch datapipe. 

If you are familiar with mmsegmentation, the core change can be started from checking [this config file](https://github.com/EarthNets/RSI-Segmentation/blob/main/configs/deeplabv3plus/deeplabv3plus_r50-d8_256x256_40k_dfc2020_ssl4eo.py). We added multispectral support of data loader, and added the DFC dataset (adjusted from Dataset4EO in the current RSI-Segmentation version). All others follow mmsegmentation workflow.

Specifically, you can clone RSI-Segmentation, install it according to the guideline, and run 
```
# for a single GPU
python tools/train.py ${CONFIG_FILE} [optional arguments]
# for multiple GPUs
sh tools/dist_train.sh ${CONFIG_FILE} ${GPU_NUM} [optional arguments]
```

The config file for DFC2020 is [`RSI-Segmentation/configs/deeplabv3plus/deeplabv3plus_r50-d8_256x256_40k_dfc2020_ssl4eo.py`](https://github.com/EarthNets/RSI-Segmentation/blob/main/configs/deeplabv3plus/deeplabv3plus_r50-d8_256x256_40k_dfc2020_ssl4eo.py). Also, refer to [`RSI-Segmentation/tools/convert_datasets/dfc2020.py`](https://github.com/EarthNets/RSI-Segmentation/blob/main/tools/convert_datasets/dfc2020.py) for dataset preparation after downloading the dataset from [IEEE dataport](https://ieee-dataport.org/competitions/2020-ieee-grss-data-fusion-contest).

The whole implementation codes are not very straightforward to digest, but you check the RSI-Segmentation / mmsegmentation documentations for details.

**Comment by RyanAmaudruz** [comment]
Great, thank you so much with the detail response. I have busy on other commitments for the past 2 weeks, so sorry for the late reply.
