### ISSUE TITLE
Dataloader Issue

### ISSUE THREAD

**Issue by moonboy12138** [zhu-xlab/SSL4EO-S12#20]
Thanks for this great resource! I'm wondering when pretraining the MAE model,  it looks like you use the "random" season transform to get the dataset in the [public code](https://github.com/zhu-xlab/SSL4EO-S12/blob/main/src/benchmark/pretrain_ssl/pretrain_mae_s2c.py) , it seems like only 25% data of the whole dataset will be used for pretraining in one epoch, am I right or I misunderstand the logic of the released codes?

**Comment by wangyi111** [comment]
Happy new year! Yes exactly, for MAE the seasons were used purely as data augmentations.

**Comment by moonboy12138** [comment]
Thank you. And a Happy New Year to you too ! In that way, MAE only uses 25% data of the dataset for pretraining, will it lower the model preformance comparing MAE which uses all 100M images?

**Comment by wangyi111** [comment]
Yes I think so, since the training steps are 1/4 compared to using all images in one epoch. This would be (very roughly) similar to using the current way and training 4x epochs. I expect certain performance gains (also more costly of course).
