### ISSUE TITLE
Micro mAP calculation

### ISSUE THREAD

**Issue by Ehzoahis** [zhu-xlab/SSL4EO-S12#23]
https://github.com/zhu-xlab/SSL4EO-S12/blob/d511fec91933b4debd0713fac2ae8c496a218d1b/src/benchmark/transfer_classification/models/data2vec/engine_for_finetuning.py#L207C9-L209C24

Is it appropriate to calculate micro mAP cumulatively? In that case the mAP will be affected by the batch size right?

**Comment by wangyi111** [comment]
Hi, thanks for the question! Yes in principle the batch size would affect the calculation result (specifically the PR curve), but very slightly in this case as micro mAP sums each label in each sample and the test sample numbers are sufficiently big. From our test experience, ranging the batch size from 64 to 1024 the score difference is within 0.2%. Generally a smaller batch size will give a bit higher score. We chose a middle size of 256 in our experiments for convenience and to compare fairly with previous works which commonly use this batch size in calculating mAP scores.

**Comment by Ehzoahis** [comment]
In that case, did you calculate the F1, precision, and recall in the same way? Are they also taking 'micro" average?

**Comment by wangyi111** [comment]
We didn't calculate F1/precision/recall for BigEarthNet (only micro mAP). However, we calculated these metrics for OSCD in a similar per-batch way, which is a binary segmentation task so by default only "micro" is possible. We used [torchmetrics](https://lightning.ai/docs/torchmetrics/stable/classification/precision.html#torchmetrics.classification.BinaryPrecision) for this.

**Comment by Ehzoahis** [comment]
Thank you for your clarification!
