### ISSUE TITLE
Question regarding locations between S1/S2

### ISSUE THREAD

**Issue by sunny1401** [zhu-xlab/SSL4EO-S12#25]
Hi - I was examining the dataset using centroid lnglat from the tiff. not all locations have data for all three (s1/s2a/s2c) - I was wondering is that was by design or maybe I have a wrong copy of the data?

**Comment by wangyi111** [comment]
Hi! They should be one-to-one matched, could you provide e.g. the index number for the scene that you have such issue with?

**Comment by sunny1401** [comment]
closing this - will update on the HF data page.
