### ISSUE TITLE
Question about linear BE DINO

### ISSUE THREAD

**Issue by jdilger** [zhu-xlab/SSL4EO-S12#26]
Hello,

This might be a bit remedial but could you tell me why you add an extra channel of zeros before getting the intermediate [results](https://github.com/zhu-xlab/SSL4EO-S12/blob/2156913c5d8e5a2c572a5b000f0d5eaed6fc3192/src/benchmark/transfer_classification/linear_BE_dino.py#L224)?   
```python
b_zeros = torch.zeros((images.shape[0],1,images.shape[2],images.shape[3]),dtype=torch.float32)
inp = torch.cat((images[:,:10,:,:],b_zeros,images[:,10:,:,:]),dim=1)
...
intermediate_output = model.get_intermediate_layers(inp, n)
```

I am using the DINO ViT-S/16 weights with a custom dataset for S2 imagery (rather than BE). When I run it as written I get a shape error `RuntimeError: Given groups=1, weight of size [384, 13, 16, 16], expected input[8, 14, 264, 264] to have 13 channels, but got 14 channels instead.`

**Comment by wangyi111** [comment]
Hi! BigEarthNet is S2 L2A with 12 channels, while our main pretrained models take S2 L1C 13 channels as input. Therefore, we pad one extra channel (B10 band) to BE input.

In your case, I suppose your data is already 13 channels, thus you don't need to pad the extra channel. You can simply remove that line of code.

**Comment by jdilger** [comment]
That makes total sense. Thanks for your response! I thought I checked the bands but it looks like I can't count 😉 .
