### ISSUE TITLE
Weights of Multimodal Pretraining

### ISSUE THREAD

**Issue by mstricker13** [zhu-xlab/SSL4EO-S12#29]
Hi,

is it possible to also upload the training scripts and resulting network weights for the multimodal configuration? (Training on both Optical and Radar data with RandomSensorDrop)

**Comment by wangyi111** [comment]
Hi, you can refer to https://github.com/zhu-xlab/DINO-MM for [RandomSenorDrop](https://github.com/zhu-xlab/DINO-MM/blob/45975d87a7dac621ee7592e2e9163caf62532ff7/models/rs_transforms.py#L82), it's essentially a simple data augmentation. Unfortunately we don't have the weights for MoCov2 with RandomSensorDrop in SSL4EO-S12 backed up, but it should be easy to implement.

**Comment by mstricker13** [comment]
I see, thanks for your quick reply!
